# Generated by Django 5.0.1 on 2024-01-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('nombres', models.CharField(default='Nombre predeterminado', max_length=100, primary_key=True, serialize=False, verbose_name='Nombres')),
                ('correo_electronico', models.EmailField(default='correo_electronico_predeterminado@example.com', max_length=254, verbose_name='Correo Electrónico')),
                ('asunto', models.CharField(default='Asunto', max_length=255)),
                ('mensaje', models.TextField(default='Mensaje predeterminado', verbose_name='Escribe tu Mensaje')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
        ),
    ]
